name: Run Spike Ultimate

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  Spike:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v3
      - name: Make binary executable
        run: chmod +x Spike && pip install flask pyngrok pymongo
      - name: Run Spike binary
        run: python3 app.py
